run:
  timeout: 5m
  skip-dirs:
    - /usr/local/go/src # Exclude standard library
    - /opt/hostedtoolcache/go # Exclude hosted Go toolchain

linters:
  enable:
    - govet
    - staticcheck
    - errcheck

issues:
  exclude-rules:
    - path: /usr/local/go/src/.* # Match files in Go's standard library
      linters:
        - govet
        - staticcheck
