name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "helm/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Build Go app
        run: go build -o go-weather-app main.go

      - name: Test Go app
        run: go test ./...

  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.1

      - name: Run golangci-lint
        run: golangci-lint run

  vulnerability-scan-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.22.0/trivy_0.22.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.22.0_Linux-64bit.deb

      - name: Run Trivy scan
        run: trivy fs --exit-code 1 --severity HIGH,CRITICAL .

  docker-push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: srishtisrivastava100343/weather-aggregator:${{ github.run_id }}

  update-tag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: docker-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v2

      - name: Update Helm chart
        run: |
          sed -i "s/tag: v1/tag: ${{ github.run_id }}/g" helm/go-weather-app-chart/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "srishtisrivastava100@gmail.com"
          git config --global user.name "sri231996"
          git add helm/go-weather-app-chart/values.yaml
          git commit -m "Update tag in Helm chart"
          git push
